#!/bin/bash

# fill it
pkgname=python-mate-desktop
pkgver=2011.10.14
pkgrel=1
pkgdesc="Python binding for Mate Desktop"
#depends="gstreamer0.10-base-plugins, mate-panel, mate-character-map, libgtop, libmatenotify, cpufrequtils"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static || return 1

	# there is some pre-compiled files on the tar
	make || return 1
	make DESTDIR="${pkgdir}" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
