# -*- python -*-
# encoding: utf-8

def configure(conf):
    conf.env.append_value('MODULES_AVAILABLE', 'braseroburn')
    if 'braseroburn' in conf.env['ENABLE_MODULES'] or 'all' in conf.env['ENABLE_MODULES']:
        if conf.pkg_check_modules('BRASEROBURN',
                                  'libbrasero-burn >= 2.29 pygobject-2.0 pygtk-2.0',
                                  mandatory=False):
            conf.env.append_value('MODULES_TO_BUILD', 'braseroburn')


def build(bld):
    if 'braseroburn' in bld.env['MODULES_TO_BUILD']:
        bld.codegen('brasero_burn', prefix='brasero_burn')
        pyext = bld.create_pyext()
        pyext.source = 'brasero_burn_module.c brasero_burn.c brasero-types.c'
        pyext.includes = '.'
        pyext.target = 'braseroburn'
        pyext.uselib = 'BRASEROBURN'
        pyext.install_path = '${PYTHONDIR}/gtk-2.0'

        bld.install_files('${DATADIR}/pygtk/2.0/defs', 'brasero_burn.defs')

