#!/bin/bash

# fill it
pkgname=python-mate
pkgver=2011.08.31
pkgrel=1
pkgdesc="Python binding for Mate"
#depends="gstreamer0.10-base-plugins, mate-panel, mate-character-map, libgtop, libmatenotify, cpufrequtils"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--enable-mate \
		--enable-mateui \
		--enable-matecanvas \
		--enable-matevfs \
		--enable-matevfsmatecomponent \
		--enable-pyvfsmodule \
		--enable-mateconf \
		--enable-matecomponent_activation \
		--enable-matecomponent \
		--enable-matecomponentui || return 1

	# there is some pre-compiled files on the tar
	make || return 1
	make DESTDIR="${pkgdir}" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
